name : ci

on:
  push:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name : checkout
              uses: actions/checkout@v7

            - name: setup node
              uses: actions/setup-node@v6
              with:
                node-version: 20
                cache: 'npm'
                cache-dependency-path: frontend/package-lock.json
            
                  # ESLint and Prettier must be in `package.json`
            - name: Install Node.js dependencies
              run: npm install --legacy-peer-deps
              working-directory: frontend

            - name: install eslint
              run: npx eslint .
              working-directory: frontend

            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                eslint: true
                prettier: true
