#goal: To run end to end devsecops CICD pipeline
name : devsecops_deployment

on:
    push:
        branches: [master]


jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    git-leaks-check:
        uses: ./.github/workflows/secret-scanning.yml

    dependency-checks:
        uses: ./.github/workflows/dependency-scan.yml

    docker-file-and-image-checks:
        uses: ./.github/workflows/docker-scan.yml