name: docker-file&image-scan

on:
    workflow_call

jobs:
    docker-file-scan:
        runs-on: ubuntu-26.04-arm
        strategy:
          matrix:
            folder: [backend, frontend]        
        steps:
            - name : checkout
              uses: actions/checkout@v7

            - name: dockerfile-scan
              uses: hadolint/hadolint-action@v3.3.0
              with:
                dockerfile: ${{ matrix.folder }}/Dockerfile
            
            - name: docker-image-build
              run: docker build -t {{ vars.DOCKERHUB_USERNAME }}/devboard-${{ matrix.folder }} .
              working-directory: ${{ matrix.folder }}
