name: code quality

on:
    workflow_call

jobs:
    git-checks:

        runs-on: ubuntu-latest
        steps:
            - name: git checkout
              uses: actions/checkout@v7
              with:
                fetch-depth: 0 # to fetch all commit and branches as we are doing secret scanning in next step

            # File: .github/workflows/detect-new-secrets.yml
            - name: Secret Scanner
              uses: secret-scanner/action@0.2.1